service/protocol-samples/http-client-di-sample/pom.xml, service/protocol-samples/http-client-to0-sample/pom.xml, service/protocol-samples/http-client-to1-sample/pom.xml, service/protocol-samples/http-client-to2-sample/pom.xml, service/protocol-samples/http-server-di-sample/pom.xml, service/protocol-samples/http-server-to0-to1-sample/pom.xml, service/protocol-samples/http-server-to2-sample/pom.xml
Updating the exec.MainClass in pom.xml for protocol-samples as per the
new packaging structure.
=> Updating execMainClass in pom.xml of protocol samples

service/component-samples/pom.xml, service/component-samples/rv/pom.xml, service/component-samples/rv/src/main/java/org/fido/iot/sample/RvContextListener.java, service/component-samples/rv/src/main/java/org/fido/iot/sample/RvServerApp.java, storage/storage-samples/storage-rv-sample/pom.xml, storage/storage-samples/storage-rv-sample/src/main/java/org/fido/iot/storage/RvsDbManager.java, storage/storage-samples/storage-rv-sample/src/main/java/org/fido/iot/storage/To0AllowListDenyListDbStorage.java, storage/storage-samples/storage-rv-sample/src/main/java/org/fido/iot/storage/To0DbStorage.java, storage/storage-samples/storage-rv-sample/src/main/resources/config.properties
- verifying if the GUID included in OV is not in denylist.
=> Checking GUID against denylist

storage/storage-samples/storage-rv-sample/src/main/java/org/fido/iot/storage/To0AllowListDenyListDbStorage.java
=> Verify GUID against denylist optimization.

service/component-samples/rv/src/main/java/org/fido/iot/sample/RvContextListener.java, storage/storage-samples/storage-rv-sample/pom.xml, storage/storage-samples/storage-rv-sample/src/main/java/org/fido/iot/storage/RvsDbManager.java, storage/storage-samples/storage-rv-sample/src/main/java/org/fido/iot/storage/To0AllowListDenyListDbStorage.java, storage/storage-samples/storage-rv-sample/src/main/resources/config.properties
Validating Supply Chain Toolkit and IOT Platform SDK Public Key verification against allowlist and denylist
=> Allowlist and Denylist verification for OV publickey

protocol/src/main/java/org/fido/iot/protocol/Const.java, protocol/src/main/java/org/fido/iot/protocol/CryptoService.java, protocol/src/main/java/org/fido/iot/protocol/To0ServerService.java, protocol/src/main/java/org/fido/iot/protocol/To1ServerService.java, protocol/src/main/java/org/fido/iot/protocol/To1ServerStorage.java, protocol/src/main/java/org/fido/iot/protocol/To2ClientService.java, protocol/src/main/java/org/fido/iot/protocol/To2ServerService.java, protocol/src/main/java/org/fido/iot/protocol/To2ServerStorage.java, protocol/src/main/java/org/fido/iot/protocol/epid/EpidHttpClient.java, protocol/src/main/java/org/fido/iot/protocol/epid/EpidMaterialService.java, protocol/src/main/java/org/fido/iot/protocol/epid/EpidSignatureVerifier.java, protocol/src/main/java/org/fido/iot/protocol/epid/EpidUtils.java, protocol/src/test/java/org/fido/iot/protocol/Ec256Test.java, protocol/src/test/java/org/fido/iot/protocol/Ec384Test.java, protocol/src/test/java/org/fido/iot/protocol/To1Test.java, protocol/src/test/java/org/fido/iot/protocol/To2Test.java, storage/storage-samples/storage-owner-sample/src/main/java/org/fido/iot/storage/OwnerDbManager.java, storage/storage-samples/storage-owner-sample/src/main/java/org/fido/iot/storage/OwnerDbStorage.java, storage/storage-samples/storage-rv-sample/src/main/java/org/fido/iot/storage/RvsDbManager.java, storage/storage-samples/storage-rv-sample/src/main/java/org/fido/iot/storage/To1DbStorage.java
- Enabling EPID support in protocol library.
=> EPID support in protocol library.

protocol/src/main/java/org/fido/iot/protocol/Const.java, protocol/src/main/java/org/fido/iot/protocol/CryptoService.java, protocol/src/main/java/org/fido/iot/protocol/To2ClientService.java, protocol/src/main/java/org/fido/iot/protocol/To2ServerService.java, protocol/src/main/java/org/fido/iot/protocol/To2ServerStorage.java, protocol/src/main/java/org/fido/iot/protocol/VoucherExtensionService.java, protocol/src/test/java/org/fido/iot/protocol/BaseTemplate.java, protocol/src/test/java/org/fido/iot/protocol/EcdhTest.java, protocol/src/test/java/org/fido/iot/protocol/To2AsymkexTest.java, storage/storage-samples/storage-owner-sample/src/main/java/org/fido/iot/storage/OwnerDbStorage.java
=> Add RSA support and ASYMKEX key exchange

service/component-samples/rv/pom.xml, service/component-samples/rv/src/main/java/org/fido/iot/sample/RvAppSettings.java, service/component-samples/rv/src/main/java/org/fido/iot/sample/RvConfigLoader.java, service/component-samples/rv/src/main/java/org/fido/iot/sample/RvContextListener.java, service/component-samples/rv/src/main/java/org/fido/iot/sample/RvServerApp.java
- The application can be configured using properties.
- Reading RV DB and Tomcat context parameters using Constants
and Configuration Loader classes.
TO-DO:
-Create README for service/component-samples/rv
=> Adding support to configure RV service component-samples using properties file.

demo/rv/Dockerfile, demo/rv/README.md, demo/rv/docker-compose.yml, demo/rv/rv-entrypoint.sh, demo/rv/rv.env, service/component-samples/rv/pom.xml
- A top-level 'demo' directory is created for RV that contains
Docker setup that configures JVM and runs the service.
TO-DOs:
- Update README at demo/rv.
=> RV standalone execution.

Jenkinsfile.yml
- Modified Jenkinsfile to create demo.tar.gz and archive demo.tar.gz
Signed-off-by: B, Prashanth Natraj <prashanth.natraj.b@intel.com>
=> Archive demo directory

demo/manufacturer/Dockerfile, demo/manufacturer/README.md, demo/manufacturer/docker-compose.yml, demo/manufacturer/manufacturer-entrypoint.sh, demo/manufacturer/manufacturer.env, service/component-samples/manufacturer/pom.xml, service/component-samples/manufacturer/src/main/java/org/fido/iot/sample/ManufacturerApiSevlet.java, service/component-samples/manufacturer/src/main/java/org/fido/iot/sample/ManufacturerApp.java, service/component-samples/manufacturer/src/main/java/org/fido/iot/sample/ManufacturerAppSettings.java, service/component-samples/manufacturer/src/main/java/org/fido/iot/sample/ManufacturerConfigLoader.java, service/component-samples/manufacturer/src/main/java/org/fido/iot/sample/ManufacturerContextListener.java, service/component-samples/pom.xml
- The code is essentially a configurable version of
protocol-samples/http-srver-di-sample. Certain properties are exposed
outside that can be passed as environment/system variables.
- Runnable manufacturer jar is created at mvn install phase that is
copied over to demo/manufacturer, along with the libs directory.
- Docker scripts have been added to demo/manufacturer.
=> Initial commit for Manufacturer Component Sample

protocol/pom.xml, service/component-samples/manufacturer/pom.xml, service/component-samples/owner/pom.xml, service/component-samples/rv/pom.xml, service/http-dispatchers/http-client-dispatcher/pom.xml, service/http-dispatchers/http-server-dispatcher/pom.xml, service/protocol-samples/http-client-di-sample/pom.xml, service/protocol-samples/http-client-to0-sample/pom.xml, service/protocol-samples/http-client-to1-sample/pom.xml, service/protocol-samples/http-client-to2-sample/pom.xml, service/protocol-samples/http-server-di-sample/pom.xml, service/protocol-samples/http-server-to0-to1-sample/pom.xml, service/protocol-samples/http-server-to2-sample/pom.xml, storage/storage-samples/storage-di-sample/pom.xml, storage/storage-samples/storage-owner-sample/pom.xml, storage/storage-samples/storage-rv-sample/pom.xml
Upgrading version of third-party package to their latest available
release.
Tomcat : 9.0.39
=> Upgrading 3rd-party package versions

protocol/src/main/java/org/fido/iot/protocol/Const.java, protocol/src/main/java/org/fido/iot/protocol/CryptoService.java, protocol/src/test/java/org/fido/iot/protocol/To2EcRsaTest.java
=> Add support for ASYMKEX3072 key exchange

pom.xml, protocol/src/main/java/org/fido/iot/protocol/ServiceInfoEncoder.java, protocol/src/main/java/org/fido/iot/protocol/To2ClientService.java, protocol/src/main/java/org/fido/iot/protocol/To2ServerService.java, service/component-samples/http-device-sample/pom.xml, service/component-samples/http-device-sample/src/main/java/org/fido/iot/sample/DeviceServiceInfoModule.java, service/component-samples/http-device-sample/src/main/java/org/fido/iot/sample/DeviceServiceInfoSequence.java, serviceinfo/pom.xml, serviceinfo/src/main/java/org/fido/iot/serviceinfo/SdoDev.java, serviceinfo/src/main/java/org/fido/iot/serviceinfo/SdoSys.java, serviceinfo/src/main/java/org/fido/iot/serviceinfo/ServiceInfo.java, serviceinfo/src/main/java/org/fido/iot/serviceinfo/ServiceInfoEntry.java, serviceinfo/src/main/java/org/fido/iot/serviceinfo/ServiceInfoMarshaller.java, serviceinfo/src/main/java/org/fido/iot/serviceinfo/ServiceInfoModule.java, serviceinfo/src/main/java/org/fido/iot/serviceinfo/ServiceInfoSequence.java, serviceinfo/src/test/java/org/fido/iot/serviceinfo/ServiceInfoMarshallerTest.java, storage/storage-samples/storage-owner-sample/pom.xml, storage/storage-samples/storage-owner-sample/src/main/java/org/fido/iot/storage/OwnerDbManager.java, storage/storage-samples/storage-owner-sample/src/main/java/org/fido/iot/storage/OwnerDbStorage.java, storage/storage-samples/storage-owner-sample/src/main/java/org/fido/iot/storage/OwnerServiceInfoModule.java, storage/storage-samples/storage-owner-sample/src/main/java/org/fido/iot/storage/OwnerServiceInfoSequence.java, storage/storage-samples/storage-owner-sample/src/test/java/org/fido/iot/storage/To2StorageTest.java
- Initial design classes for serviceinfo implementation.
=> Owner and Device ServiceInfo Implementation.

protocol/src/main/java/org/fido/iot/protocol/KeyStoreResolver.java, service/component-samples/owner/src/main/java/org/fido/iot/sample/OwnerServerApp.java, service/component-samples/pom.xml, service/component-samples/reseller/pom.xml, service/component-samples/reseller/src/main/java/org/fido/iot/sample/ResellerAppConstants.java, service/component-samples/reseller/src/main/java/org/fido/iot/sample/ResellerConfigLoader.java, service/component-samples/reseller/src/main/java/org/fido/iot/sample/ResellerContextListener.java, service/component-samples/reseller/src/main/java/org/fido/iot/sample/ResellerCustomerServlet.java, service/component-samples/reseller/src/main/java/org/fido/iot/sample/ResellerDbManager.java, service/component-samples/reseller/src/main/java/org/fido/iot/sample/ResellerServerApp.java, service/component-samples/reseller/src/main/java/org/fido/iot/sample/ResellerVoucherServlet.java, service/http-api-samples/http-api-di-sample/pom.xml, service/http-api-samples/http-api-di-sample/src/main/java/org/fido/iot/api/DiApiServlet.java, service/http-api-samples/http-api-keystore-sample/pom.xml, service/http-api-samples/http-api-keystore-sample/src/main/java/org/fido/iot/api/KeyStoreServlet.java, service/http-api-samples/http-api-owner-sample/pom.xml, service/http-api-samples/http-api-owner-sample/src/main/java/org/fido/iot/api/OwnerVoucherServlet.java, service/http-api-samples/http-api-rv-sample/pom.xml, service/http-api-samples/pom.xml, service/pom.xml, service/protocol-samples/http-server-di-sample/pom.xml, service/protocol-samples/http-server-di-sample/src/main/java/org/fido/iot/sample/DiApp.java, service/protocol-samples/http-server-to2-sample/pom.xml, service/protocol-samples/http-server-to2-sample/src/main/java/org/fido/iot/sample/To2ServerApp.java, storage/storage-samples/storage-owner-sample/src/main/java/org/fido/iot/storage/OwnerDbManager.java
Added Reseller component and REST APIS
=> Adding Reseller component and REST APIs

service/http-api-samples/pom.xml
=> Update parent POM for http-api-samples

service/component-samples/manufacturer/pom.xml, service/component-samples/owner/pom.xml, service/component-samples/rv/pom.xml
- Adding plugin to owner component sample.
- Updating plugin version in rv and manufacturer component samples.
=> Maven clean plugin for component samples

README.md, demo/README.md, demo/device/README.md, demo/manufacturer/README.md, demo/owner/README.md, demo/reseller/README.md, demo/rv/README.md
- Updated top level README for protocol samples folder structure change.
- Added steps to run component sample services.
- Added runtime properties used by each service in component-samples
and their default values.
- Added README for demo folder with necessary docker commands
- Updated README for each component in demo folder.
=> README Update

protocol/src/main/java/org/fido/iot/protocol/CryptoService.java, protocol/src/test/java/org/fido/iot/protocol/BaseTemplate.java, protocol/src/test/java/org/fido/iot/protocol/Ec256Test.java, protocol/src/test/java/org/fido/iot/protocol/Ec384Test.java, protocol/src/test/java/org/fido/iot/protocol/EcdhTest.java, service/http-dispatchers/http-server-dispatcher/src/test/java/org/fido/iot/sample/TestListener.java
- Creating a thread safe SecureRandom function initialization.
=> Updating SecureRandom function initialization.

demo/manufacturer/Dockerfile, demo/owner/Dockerfile, demo/reseller/Dockerfile, demo/rv/Dockerfile
- Installing haveged for better entropy inside docker containers.
=> Installing haveged for entropy in docker containers

service/protocol-samples/http-client-to2-sample/src/main/java/org/fido/iot/sample/To2ClientApp.java
- Updated To2ClientApp to return valid secret in case reuse is false,
else return null.
=> Update Protocok sample To2 Client for resale

service/component-samples/reseller/src/main/java/org/fido/iot/sample/ResellerDbManager.java
'ovh' was created, but never used.
=> Fix Klocwork issue

cert-utils/pom.xml, protocol/pom.xml, protocol/src/test/java/org/fido/iot/protocol/To2EcRsaTest.java, service/component-samples/http-device-sample/pom.xml, service/component-samples/http-device-sample/src/main/java/org/fido/iot/sample/CredentialStorage.java, service/component-samples/http-device-sample/src/main/java/org/fido/iot/sample/Device.java, service/component-samples/http-device-sample/src/main/java/org/fido/iot/sample/DeviceServiceInfoModule.java, service/component-samples/http-device-sample/src/main/java/org/fido/iot/sample/DeviceServiceInfoSequence.java, service/component-samples/manufacturer/pom.xml, service/component-samples/owner/pom.xml, service/component-samples/rv/pom.xml, service/component-samples/rv/src/main/java/org/fido/iot/sample/RvAppSettings.java, service/component-samples/rv/src/main/java/org/fido/iot/sample/RvConfigLoader.java, service/http-dispatchers/http-client-dispatcher/pom.xml, service/http-dispatchers/http-server-dispatcher/pom.xml, service/http-dispatchers/pom.xml, service/protocol-samples/http-client-di-sample/pom.xml, service/protocol-samples/http-client-to0-sample/pom.xml, service/protocol-samples/http-client-to1-sample/pom.xml, service/protocol-samples/http-client-to2-sample/pom.xml, service/protocol-samples/http-server-di-sample/pom.xml, service/protocol-samples/http-server-to0-to1-sample/pom.xml, service/protocol-samples/pom.xml, serviceinfo/pom.xml, storage/pom.xml, storage/storage-samples/pom.xml, storage/storage-samples/storage-di-sample/pom.xml, storage/storage-samples/storage-owner-sample/pom.xml, storage/storage-samples/storage-rv-sample/pom.xml
Adding Apache License Header to the project files.
=> Adding Apache License Header

pom.xml, util/storage-samples/storage-rv-sample/pom.xml
Updating demo folder address in POM file.
=> Updating demo folder address in POM file.

component-samples/http-device-sample/src/main/java/org/fido/iot/sample/Device.java
=> Use 512 bit secret in PRI device

component-samples/http-device-sample/src/main/java/org/fido/iot/sample/Device.java, protocol/src/main/java/org/fido/iot/protocol/Const.java, protocol/src/main/java/org/fido/iot/protocol/CryptoService.java, protocol/src/test/java/org/fido/iot/protocol/To2Ccm128Test.java, protocol/src/test/java/org/fido/iot/protocol/To2Ccm256Test.java, protocol/src/test/java/org/fido/iot/protocol/To2Gcm128Test.java, protocol/src/test/java/org/fido/iot/protocol/To2Gcm256Test.java
=> Add CCM & GCM encryption

protocol/src/test/java/org/fido/iot/protocol/CompositeTest.java, protocol/src/test/java/org/fido/iot/protocol/CryptoServiceTest.java, protocol/src/test/java/org/fido/iot/protocol/MessageDispatcherTest.java, protocol/src/test/java/org/fido/iot/protocol/RendezvousBlobDecoderTest.java, protocol/src/test/java/org/fido/iot/protocol/RendezvousInfoDecoderTest.java
Adding unit tests to the Protocol component.
=> Adding unit tests to Protocol component

util/storage-samples/storage-di-sample/src/test/java/org/fido/iot/storage/DiStorageTest.java, util/storage-samples/storage-owner-sample/src/test/java/org/fido/iot/storage/To2StorageTest.java, util/storage-samples/storage-rv-sample/src/test/java/org/fido/iot/storage/RvsStorageTest.java
Adding unit tests to Storage-Sample components.
=> Adding unit tests to Storage-Sample component

protocol/src/main/java/org/fido/iot/protocol/Const.java, protocol/src/main/java/org/fido/iot/protocol/CryptoService.java, protocol/src/main/java/org/fido/iot/protocol/KeyExchangeResult.java, protocol/src/main/java/org/fido/iot/protocol/ServiceInfoEncoder.java, protocol/src/main/java/org/fido/iot/protocol/To2ClientService.java, protocol/src/main/java/org/fido/iot/protocol/To2ServerService.java, protocol/src/test/java/org/fido/iot/protocol/EcdhTest.java, protocol/src/test/java/org/fido/iot/protocol/To2Cbc128Test.java, protocol/src/test/java/org/fido/iot/protocol/To2Cbc256Test.java
Several mismatches between this PRI and the latest FDO spec have been found.  Correct them.
=> Fix spec mismatches

README.md, component-samples/demo/README.md
protocol-sample directory corrections
clarifaction on use of pre-prod and emulated devices
=> README updates

README.md, component-samples/demo/README.md, component-samples/demo/device/README.md, component-samples/demo/manufacturer/README.md, component-samples/demo/owner/README.md, component-samples/demo/reseller/README.md, component-samples/demo/rv/README.md
=> Updating README for 1.11 release

component-samples/owner/src/main/java/org/fidoalliance/fdo/sample/OwnerServerApp.java
present in protocol samples but missing in component samples
=> Added serviceinfo servlet to component samples

util/storage-samples/storage-owner-sample/src/main/java/org/fidoalliance/fdo/storage/OwnerDbStorage.java
=> Fix GUID reassignment with no key data

util/storage-samples/storage-owner-sample/src/main/java/org/fidoalliance/fdo/storage/OwnerDbStorage.java
- To prevent a greedy device from hogging the owner, adding an upper
limit to to the MTU size requested by device.
=> Capping MTU size requested by device by owner threshold value.

component-samples/manufacturer/src/main/java/org/fidoalliance/fdo/sample/ManufacturerCustomerServlet.java, http-api-samples/http-api-di-sample/src/main/java/org/fidoalliance/fdo/api/AssignCustomerServlet.java, http-api-samples/http-api-di-sample/src/main/java/org/fidoalliance/fdo/api/RvInfoServlet.java, util/storage-samples/storage-di-sample/src/main/java/org/fidoalliance/fdo/storage/DiDbManager.java
- Adding checks to api/v1/rvinfo
- Adding checks to api/v1/customers
- Adding checks to api/v1/assign
=> Adding input sanity checks to Manufacturer APIs

http-api-samples/http-api-owner-sample/src/main/java/org/fidoalliance/fdo/api/OwnerDeviceTypeCriteriaServlet.java, util/serviceinfo/src/main/java/org/fidoalliance/fdo/serviceinfo/ModuleManager.java, util/storage-samples/storage-owner-sample/src/main/java/org/fidoalliance/fdo/storage/OwnerDbManager.java, util/storage-samples/storage-owner-sample/src/main/java/org/fidoalliance/fdo/storage/OwnerSysModule.java
Fixing Klocwork issues by
- Removing unused variables.
- Removing unused private methods.
=> Fixing Klocwork Issues

util/storage-samples/storage-owner-sample/src/main/java/org/fidoalliance/fdo/storage/OwnerDbStorage.java
=> Don't expose references to internal data via getters

component-samples/http-device-sample/src/main/java/org/fidoalliance/fdo/sample/Device.java
=> Don't ignore exceptions during onboarding

http-api-samples/http-api-owner-sample/src/main/java/org/fidoalliance/fdo/api/OwnerSystemResourceServlet.java
=> added missing statement for where clause

component-samples/http-device-sample/src/main/java/org/fidoalliance/fdo/sample/Device.java
Fixing exception logging in PRI device during T02.
=> Fixing exception logging in PRI device

component-samples/http-device-sample/src/main/java/org/fidoalliance/fdo/sample/Device.java
Fixing T02 completion conditional check in T02.
=> Fixing T02 completion conditional check

component-samples/owner/src/main/java/org/fidoalliance/fdo/sample/OwnerServerApp.java
Adding authentication check for svi APIs.
=> Adding authentication check for svi APIs

protocol/src/main/java/org/fidoalliance/fdo/protocol/CryptoService.java
=> Enhance input validation on tag len and AAD of GCM

protocol/src/main/java/org/fidoalliance/fdo/protocol/CryptoService.java
=> Use AEADParameters instead of CCMParameters

build/Dockerfile, build/README.md, build/build.sh, build/docker-compose.yml
Create a docker based scripts to build the source code.
=> Prepare docker build scripts

protocol-samples/http-server-to2-sample/src/main/java/org/fidoalliance/fdo/sample/To2ContextListener.java, util/serviceinfo/src/main/java/org/fidoalliance/fdo/serviceinfo/ModuleManager.java, util/storage-samples/storage-owner-sample/src/main/java/org/fidoalliance/fdo/storage/OwnerDbManager.java, util/storage-samples/storage-owner-sample/src/main/java/org/fidoalliance/fdo/storage/OwnerDbStorage.java, util/storage-samples/storage-owner-sample/src/main/java/org/fidoalliance/fdo/storage/OwnerSysModule.java
also, add some user messages when mtu size is adjusted
beyond the lower or upper limits allowed
=> adjust FILE_WRITE chunk size based on mtu

protocol/src/main/java/org/fidoalliance/fdo/protocol/CryptoService.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/DiffieHellman.java, protocol/src/test/java/org/fidoalliance/fdo/protocol/DiffieHellmanTest.java, protocol/src/test/java/org/fidoalliance/fdo/protocol/To2KeyExchangeTest.java
=> Add Diffie-Hellman key exchanges

protocol/src/main/java/org/fidoalliance/fdo/protocol/CryptoService.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/DiffieHellman.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/VoucherExtensionService.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/epid/EpidHttpClient.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/epid/EpidMaterialService.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/epid/EpidSignatureVerifier.java
=> Make leaf classes final

protocol/src/main/java/org/fidoalliance/fdo/protocol/CryptoService.java
=> Destroy secrets when we're done with them

pom.xml
Added PGP plugin in the base `pom.xml` file for signature verification.
=> Added PGP plugin in pom.xml

component-samples/scripts/keys_gen.sh
=> Keys generation

protocol/src/main/java/org/fidoalliance/fdo/protocol/RendezvousInfoDecoder.java
Updating the default value of rvProt from HTTP to HTTPS.
=> Updating the default value of rvProt

component-samples/aio/src/main/java/org/fidoalliance/fdo/sample/AioAppSettings.java, component-samples/aio/src/main/java/org/fidoalliance/fdo/sample/AioContextListener.java, component-samples/aio/src/main/java/org/fidoalliance/fdo/sample/AioDbManager.java, component-samples/aio/src/main/java/org/fidoalliance/fdo/sample/AioServerApp.java, component-samples/demo/aio/aio.env
Making to0RvBlob configurable in AIO.
=> Making to0RvBlob in AIO configurable

component-samples/demo/scripts/keys_gen.sh
After switching to non-root user, the folder target/tomcat should be
pre-created, otherwise there are issues while creating new files within
that folder.
=> Fix failure to start reseller docker

component-samples/demo/manufacturer/README.md, http-api-samples/http-api-di-sample/src/main/java/org/fidoalliance/fdo/api/AssignCustomerServlet.java, util/storage-samples/storage-di-sample/src/main/java/org/fidoalliance/fdo/storage/DiDbManager.java
=> changed customer assign api from guid to serial no

component-samples/manufacturer/src/main/java/org/fidoalliance/fdo/sample/ManufacturerApp.java, component-samples/owner/src/main/java/org/fidoalliance/fdo/sample/OwnerServerApp.java, component-samples/rv/src/main/java/org/fidoalliance/fdo/sample/RvServerApp.java, protocol-samples/http-server-di-sample/src/main/java/org/fidoalliance/fdo/sample/DiApp.java, protocol-samples/http-server-to0-to1-sample/src/main/java/org/fidoalliance/fdo/sample/To0To1ServerApp.java, protocol-samples/http-server-to2-sample/src/main/java/org/fidoalliance/fdo/sample/To2ServerApp.java
=> Wire Error-Type255 (msg/255) in server applications

component-samples/http-device-sample/src/main/java/org/fidoalliance/fdo/sample/Device.java, component-samples/owner/src/main/java/org/fidoalliance/fdo/sample/OwnerContextListener.java, component-samples/owner/src/main/java/org/fidoalliance/fdo/sample/OwnerTo0Client.java, protocol-samples/http-client-di-sample/src/main/java/org/fidoalliance/fdo/sample/DiClientApp.java, protocol-samples/http-client-to0-sample/src/main/java/org/fidoalliance/fdo/sample/To0ClientApp.java, protocol-samples/http-client-to1-sample/src/main/java/org/fidoalliance/fdo/sample/To1ClientApp.java, protocol-samples/http-client-to2-sample/src/main/java/org/fidoalliance/fdo/sample/To2ClientApp.java, util/http-dispatchers/http-client-dispatcher/src/main/java/org/fidoalliance/fdo/sample/HttpResponseCodeException.java, util/http-dispatchers/http-client-dispatcher/src/main/java/org/fidoalliance/fdo/sample/WebClient.java
=> Fail cleanly when connection is refused

protocol/src/main/java/org/fidoalliance/fdo/protocol/epid/EpidSignatureVerifier.java
=> fix error with EPID signature construction

component-samples/http-device-sample/src/main/java/org/fidoalliance/fdo/sample/Device.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/RendezvousInfoDecoder.java
=> Respsect DelaySec when connecting to TO1 service

component-samples/aio/src/main/java/org/fidoalliance/fdo/sample/AioContextListener.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/MessageDispatcher.java, util/http-dispatchers/http-server-dispatcher/src/main/java/org/fidoalliance/fdo/sample/ProtocolHandler.java
=> fixed server 255 error handlers

component-samples/http-device-sample/src/main/java/org/fidoalliance/fdo/sample/Device.java
Adding IOException handling structure over WebClient object.
=> Adding IOException handling structure over WebClient object

component-samples/http-device-sample/src/main/java/org/fidoalliance/fdo/sample/Device.java
=> Don't fail exceptionally if TO2 server returns error codes

pom.xml
=> Update tomcat version to 9.0.52

build/README.md, component-samples/demo/README.md
Adding documentation for supported Docker version.
=> Adding documentation for supported Docker version

README.md, component-samples/demo/README.md, component-samples/demo/aio/Podmanfile, component-samples/demo/aio/README.md, component-samples/demo/manufacturer/Podmanfile, component-samples/demo/manufacturer/README.md, component-samples/demo/owner/Podmanfile, component-samples/demo/owner/README.md, component-samples/demo/reseller/Podmanfile, component-samples/demo/reseller/README.md, component-samples/demo/rv/Podmanfile, component-samples/demo/rv/README.md, component-samples/demo/scripts/enable_rhel_support.sh
Signed-off-by: Shrikant Temburwar <shrikant.temburwar@intel.com>
=> Add FDO support on RHEL 8

protocol/src/main/java/org/fidoalliance/fdo/protocol/Const.java
Updating EAT-NONCE value from 9 to 10.
Updating EAT-UEID  value from 10 to 11.
=> Updating EAT IANA number

protocol/src/main/java/org/fidoalliance/fdo/protocol/Const.java
Revert commit "Updating EAT IANA number (#359)"
=> Revert "Updating EAT IANA number (#359)"

README.md, protocol-samples/http-server-to0-to1-sample/src/main/java/org/fidoalliance/fdo/sample/To0To1ContextListener.java, protocol-samples/http-server-to0-to1-sample/src/main/java/org/fidoalliance/fdo/sample/To0To1ServerApp.java, protocol-samples/http-server-to2-sample/src/main/java/org/fidoalliance/fdo/sample/To2ContextListener.java, protocol-samples/http-server-to2-sample/src/main/java/org/fidoalliance/fdo/sample/To2ServerApp.java
=> add epid test mode setting to Rendezvous and Owner protocol samples.

component-samples/http-device-sample/src/main/java/org/fidoalliance/fdo/sample/DeviceSysModule.java, util/serviceinfo/src/main/java/org/fidoalliance/fdo/serviceinfo/FdoSys.java, util/storage-samples/storage-owner-sample/src/main/java/org/fidoalliance/fdo/storage/OwnerDbManager.java, util/storage-samples/storage-owner-sample/src/main/java/org/fidoalliance/fdo/storage/OwnerSysModule.java
=> added keep alive message processing to SysModule

component-samples/aio/src/main/java/org/fidoalliance/fdo/sample/AioContextListener.java
Adding DI session cleaner to scheduled AIO thread.
=> Removing DI sessions from AIO Database

util/storage-samples/storage-owner-sample/src/main/java/org/fidoalliance/fdo/storage/OwnerSysModule.java
=> fix error with fdosys fetch

Jenkinsfile.yml
Cleaning test workspace in build machine.
=> Cleaning test workspace in build machine

component-samples/demo/aio/service.yml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/service.yml, component-samples/demo/reseller/service.yml, component-samples/demo/rv/service.yml, component-samples/device/src/main/java/org/fidoalliance/fdo/sample/DeviceApp.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/StandardHttpServer.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/api/MfgVoucher.java
Updating default port number in docker-compose files.
=> Updating default port number in docker-compose files

component-samples/demo/manufacturer/docker-compose.yml, component-samples/demo/owner/docker-compose.yml, component-samples/demo/reseller/docker-compose.yml, component-samples/demo/rv/docker-compose.yml
Exposing HTTP and HTTPS ports in docker-compose file.
Creating a mountable app-data folder.
=> Exposing HTTP and HTTPS ports in docker-compose file

Jenkinsfile.yml
Enabling smoketest in Jenskinsfile.yml.
=> Enabling smoketest in Jenskinsfile.yml

component-samples/demo/scripts/extend_upload.sh
Script to extend and upload OV to Owner.
Signed-off-by: Anapareddy, Sai Anudeep <sai.anudeep.anapareddy@intel.com>
=> Script to extend and upload OV to Owner

protocol/src/main/java/org/fidoalliance/fdo/protocol/serialization/CoseKeySerializer.java
=> fix logic with cosekey serialization

component-samples/demo/aio/service.yml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/service.yml, component-samples/demo/reseller/service.yml, component-samples/demo/rv/service.yml, component-samples/demo/scripts/keys_gen.sh
Adding script to generate secure credentials.
=> Adding script to generate secure credentials

component-samples/demo/manufacturer/WEB-INF/web.xml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/WEB-INF/web.xml, component-samples/demo/owner/docker-compose.yml, component-samples/demo/owner/service.yml, component-samples/demo/rv/docker-compose.yml, component-samples/demo/rv/service.yml, component-samples/demo/scripts/extend_upload.sh, component-samples/demo/scripts/keys_gen.sh
=> Changes for E2E enablement

component-samples/demo/manufacturer/WEB-INF/web.xml, component-samples/demo/manufacturer/hibernate.cfg.xml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/WEB-INF/web.xml, component-samples/demo/owner/hibernate.cfg.xml, component-samples/demo/owner/service.yml
=> added OnDie and EPID config to individual components

component-samples/aio/src/main/java/org/fidoalliance/fdo/sample/AioApp.java, component-samples/device/src/main/java/org/fidoalliance/fdo/sample/FdoSysDeviceModule.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/Config.java
=> Logs for automation support

component-samples/demo/owner/README.md, component-samples/demo/owner/service.yml
Owner proxy setup for docker container.
=> Owner proxy setup

component-samples/demo/owner/service.yml
Added Owner proxy setup for docker container.
Signed-off-by: Himanshu <himanshu@intel.com>
=> Added proxy setup to Owner's service.yml

protocol/src/main/java/org/fidoalliance/fdo/protocol/StandardMessageDispatcher.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/api/AllowList.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/api/OwnerVoucher.java
Delete REST endpoints for APIs.
=> Delete REST endpoints for APIs

build/docker-compose.yml
Builder docker compose file updates.
=> Builder docker compose file updates

component-samples/demo/README.MD
=> updated README with OnDie instructions

component-samples/demo/manufacturer/service.yml, protocol/src/main/java/org/fidoalliance/fdo/protocol/HttpClient.java
- Logging UX fixes
- Changing the default owner port for MFG.
=> Logging UX fixes

protocol/src/main/java/org/fidoalliance/fdo/protocol/db/AutoInjectVoucherStorageFunction.java
Updating Voucher auto injection logs.
=> Updating Voucher auto injection logs

protocol/src/main/java/org/fidoalliance/fdo/protocol/api/To0Starter.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/db/StandardAcceptOwnerFunction.java
=> Updating TO0 completion logs

NOTICE, NOTICES/APACHE-HTTPCLIENT, NOTICES/APACHE-TOMCAT
Adding NOTICE files for new dependencies.
=> Adding NOTICE files for new dependencies

NOTICE, NOTICES/JAVAX-SERVLET-API
=> Updating NOTICE files

component-samples/aio/pom.xml, component-samples/demo/aio/service.yml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/service.yml, component-samples/demo/reseller/service.yml, component-samples/demo/rv/service.yml, component-samples/device/pom.xml, component-samples/pom.xml, pom.xml, protocol/pom.xml, protocol/src/test/java/org/fidoalliance/fdo/protocol/HibernateTest.java
Version rollover to 1.1.0 Release.
=> Version rollover to 1.1.0 Release

component-samples/aio/pom.xml, component-samples/demo/aio/service.yml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/service.yml, component-samples/demo/reseller/service.yml, component-samples/demo/rv/service.yml, component-samples/device/pom.xml, component-samples/pom.xml, pom.xml, protocol/pom.xml
Version rollover to 1.1.0.1-SNAPSHOT.
=> Version rollover to 1.1.0.1-SNAPSHOT

pom.xml, protocol/pom.xml
Upgrading dependency to latest version.
=> Upgrading dependency to latest version

protocol/src/main/java/org/fidoalliance/fdo/protocol/serialization/EatPayloadBaseDeserializer.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/serialization/EatPayloadBaseSerializer.java
=> Reverting UEID changes

component-samples/demo/aio/README.md, component-samples/demo/aio/service.yml, component-samples/demo/owner/README.md, component-samples/demo/owner/service.yml, protocol/src/main/java/org/fidoalliance/fdo/protocol/db/BasicServiceInfoClientSupplier.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/db/FdoSysOwnerModule.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/db/ServiceInfoHttpClientSupplier.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/db/StandardServiceInfoClientSupplier.java
=> added basic auth support for serviceinfo requests

component-samples/demo/README.MD, component-samples/demo/aio/service.yml, component-samples/demo/owner/service.yml
Instructions for secure deployment.
=> Instructions for secure deployment

component-samples/demo/README.MD
Notes for H2 database file size.
=> Notes for H2 database file size

NOTICE, NOTICES/APACHE-LOG4J-NOTICE, NOTICES/JAVAX-SERVLET-API, NOTICES/OPENJDK-NOTICE, component-samples/demo/aio/service.yml, component-samples/demo/owner/README.md
=> Updates to NOTICE files

component-samples/demo/README.MD, component-samples/demo/aio/service.yml, component-samples/demo/owner/README.md, component-samples/demo/owner/service.yml
README changes for HTTPClientSuppliers.
=> README changes

component-samples/aio/pom.xml, component-samples/demo/aio/service.yml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/service.yml, component-samples/demo/reseller/service.yml, component-samples/demo/rv/service.yml, component-samples/device/pom.xml, component-samples/pom.xml, pom.xml, protocol/pom.xml
Version rollover to 1.1.0.1 Release.
=> Version rollover to 1.1.0.1 Release

component-samples/aio/pom.xml, component-samples/demo/aio/service.yml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/service.yml, component-samples/demo/reseller/service.yml, component-samples/demo/rv/service.yml, component-samples/device/pom.xml, component-samples/pom.xml, pom.xml, protocol/pom.xml
Version rollover to 1.1.0.2-SNAPSHOT.
=> Version rollover to 1.1.0.2-SNAPSHOT

README.md, component-samples/demo/README.MD
=> added note for haveged and removed module_name:active=true from docs

component-samples/aio/pom.xml, component-samples/demo/aio/service.yml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/service.yml, component-samples/demo/reseller/service.yml, component-samples/demo/rv/service.yml, component-samples/device/pom.xml, component-samples/pom.xml, pom.xml, protocol/pom.xml
Version rollover to 1.1.0.2 Release.
=> Version rollover to 1.1.0.2 Release

component-samples/aio/pom.xml, component-samples/demo/aio/service.yml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/service.yml, component-samples/demo/reseller/service.yml, component-samples/demo/rv/service.yml, component-samples/device/pom.xml, component-samples/pom.xml, pom.xml, protocol/pom.xml
Version rollover to 1.1.1-SNAPSHOT.
=> Version rollover to 1.1.1-SNAPSHOT

component-samples/demo/README.MD, component-samples/demo/scripts/enable_podman_support.sh
Update enable podman support script
Signed-off-by: Shrikant Temburwar <shrikant.temburwar@intel.com>
=> Update enable podman support script

protocol/src/main/java/org/fidoalliance/fdo/protocol/db/OnboardConfigSupplier.java
Changing the default T02_RVblob value.
=> Changing the default T02_RVblob

protocol/src/main/java/org/fidoalliance/fdo/protocol/db/AutoInjectVoucherStorageFunction.java
Fixing AutoInject to support different RVInfo and T02Blob entries.
=> Fixing AutoInject to support different RVInfo and T02Blob entries

README.md, component-samples/demo/README.MD, component-samples/demo/aio/README.md, component-samples/demo/manufacturer/README.md, component-samples/demo/owner/README.md, component-samples/demo/reseller/README.md, component-samples/demo/rv/README.md
Updating docs for U22 support.
=> Updating docs for U22 support

README.md, build/README.md
=> Fixing url in README.md

component-samples/aio/pom.xml, component-samples/demo/aio/service.yml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/service.yml, component-samples/demo/reseller/service.yml, component-samples/demo/rv/service.yml, component-samples/device/pom.xml, component-samples/pom.xml, pom.xml, protocol/pom.xml
Version rollover to 1.1.1 Release.
=> Version rollover to 1.1.1 Release

component-samples/aio/pom.xml, component-samples/demo/aio/service.yml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/service.yml, component-samples/demo/reseller/service.yml, component-samples/demo/rv/service.yml, component-samples/device/pom.xml, component-samples/pom.xml, pom.xml, protocol/pom.xml
Version rollover to 1.1.3 SNAPSHOT.
=> Version rollover to 1.1.3 SNAPSHOT

pom.xml, protocol/src/main/java/org/fidoalliance/fdo/protocol/PemKeyStoreImpl.java
Upgrade dependencies to latest version:
snakeyaml 1.30 ==> 1.32
=> Upgrade dependencies to latest version

component-samples/demo/aio/service.yml, component-samples/device/src/main/java/org/fidoalliance/fdo/sample/FdoSysDeviceModule.java
Fixing exec_cb bug and changing default owner port
of aio.
=> Fixing exec_cb bug

component-samples/demo/aio/Dockerfile-slim, component-samples/demo/manufacturer/Dockerfile-slim, component-samples/demo/owner/Dockerfile-slim, component-samples/demo/reseller/Dockerfile-slim, component-samples/demo/rv/Dockerfile-slim
Fixing Alpine image to copy config files.
=> Fixing Alpine image to copy config files

build/build.sh, component-samples/demo/device/service.yml
=> Changing the default worker

component-samples/demo/README.MD, protocol/pom.xml, protocol/src/main/java/org/fidoalliance/fdo/protocol/EmbeddedDatabaseServer.java
Enabling embedded database for PRI services.
=> Enabling embedded database

component-samples/demo/aio/log4j2.xml, component-samples/demo/manufacturer/service.env, protocol/src/main/java/org/fidoalliance/fdo/protocol/Config.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/KeyResolver.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/StandardHttpServer.java, protocol/src/test/resources/log4j2.xml
Addressing security review comments.
=> Addressing security review comments

protocol/src/main/java/org/fidoalliance/fdo/protocol/Config.java
Changing logger in Config.java.
=> Changing logger in Config.java

component-samples/demo/README.MD
=> Adding NOTE for RHEL proxy

component-samples/aio/pom.xml, component-samples/demo/aio/service.yml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/service.yml, component-samples/demo/reseller/service.yml, component-samples/demo/rv/service.yml, component-samples/device/pom.xml, component-samples/pom.xml, pom.xml, protocol/pom.xml
Version rollover to 1.1.4-SNAPSHOT.
=> Version rollover to 1.1.4-SNAPSHOT

component-samples/demo/aio/context.xml, component-samples/demo/manufacturer/context.xml, component-samples/demo/owner/context.xml, component-samples/demo/reseller/context.xml, component-samples/demo/rv/context.xml, pom.xml
Masking Tomcat Version to reduce information disclosure.
=> Masking Tomcat Version

protocol/src/main/java/org/fidoalliance/fdo/protocol/EpidService.java
Making epid url configurable from service.yml.
=> Making epid url configurable from service.yml

component-samples/aio/pom.xml, component-samples/demo/README.MD, pom.xml, protocol/pom.xml
Adding support for the following Databases out of the box:
+ Derby
+ H2 database
+ mariaDB
+ MySQL
+ Postgres DB
=> Adding support for multiple Databases

protocol/src/main/java/org/fidoalliance/fdo/protocol/StandardMessageDispatcher.java
Fixing the issue of Double Extension of OwnershipVoucher
with a malicious owner.
=> Fixing the issue of Double Extension

Jenkinsfile.yml
Updating JenkinsFile for new deployment mode.
=> Updating JenkinsFile for new deployment mode

protocol/src/main/java/org/fidoalliance/fdo/protocol/db/OnDieCertificateManager.java
Fix for supporting Postgres DB.
=> Fix for supporting Postgres DB

component-samples/demo/README.MD
Adding README for multiple database support.
=> Adding README for multiple database support

component-samples/aio/pom.xml, component-samples/demo/aio/service.yml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/service.yml, component-samples/demo/reseller/service.yml, component-samples/demo/rv/service.yml, component-samples/device/pom.xml, component-samples/pom.xml, pom.xml, protocol/pom.xml
Version rollover to 1.1.4 Release.
=> Version rollover to 1.1.4 Release

component-samples/aio/pom.xml, component-samples/demo/aio/service.yml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/service.yml, component-samples/demo/reseller/service.yml, component-samples/demo/rv/service.yml, component-samples/device/pom.xml, component-samples/pom.xml, pom.xml, protocol/pom.xml
Version rollover to 1.1.5 SNAPSHOT.
=> Version rollover to 1.1.5 SNAPSHOT

protocol/src/main/java/org/fidoalliance/fdo/protocol/api/HealthApi.java
Updating healthCheck status for PRI components.
=> Updating healthCheck status for PRI components

pom.xml
Upgrading MySQL library to the latest version.
=> Upgrading MySQL library to the latest version

component-samples/device/src/main/java/org/fidoalliance/fdo/sample/FdoSysDeviceModule.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/HttpClient.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/message/Nonce.java, protocol/src/test/java/org/fidoalliance/fdo/protocol/ApiTest.java, protocol/src/test/java/org/fidoalliance/fdo/protocol/OwnerPublicKeyTest.java, protocol/src/test/java/org/fidoalliance/fdo/protocol/SerializationTest.java
Fixing Coverity scan findings.
=> Fixing Coverity scan findings

pom.xml, protocol/src/main/java/org/fidoalliance/fdo/protocol/HttpClient.java
=> Fixing HttpClient retry bug

component-samples/aio/pom.xml, component-samples/demo/aio/service.yml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/service.yml, component-samples/demo/reseller/service.yml, component-samples/demo/rv/service.yml, component-samples/device/pom.xml, component-samples/pom.xml, pom.xml, protocol/pom.xml
Version rollover to 1.1.5 Release.
=> Version rollover to 1.1.5 Release

pom.xml
Upgrading Tomcat Version from 10.1.7 to 10.1.8
=> Upgrading Tomcat Version

protocol/src/main/java/org/fidoalliance/fdo/protocol/api/OwnerVoucher.java
Updating OwnerVoucher REST endpoint.
=> Updating OwnerVoucher REST endpoint

component-samples/aio/pom.xml, component-samples/demo/aio/service.yml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/service.yml, component-samples/demo/reseller/service.yml, component-samples/demo/rv/service.yml, component-samples/device/pom.xml, component-samples/pom.xml, pom.xml, protocol/pom.xml
Version rollover to 1.1.5.1 Release.
=> Version rollover to 1.1.5.1 Release

component-samples/demo/db/README.md, component-samples/demo/db/custom/config-file.cnf
Removing deprecated variables from MariaDB config file.
=> Removing deprecated variables from MariaDB config file

component-samples/device/src/main/java/org/fidoalliance/fdo/sample/FdoSysDeviceModule.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/CertChainBuilder.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/StandardCryptoService.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/StandardHttpServer.java
- Fixing Coverity findings.
- Adding support for HTTP2.
=> Fixing Coverity findings and adding support for HTTP2

protocol/src/main/java/org/fidoalliance/fdo/protocol/ProtocolServlet.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/db/FdoSysOwnerModule.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/message/Guid.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/message/Hash.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/message/Nonce.java
=> Fixing Coverity Findings

build/Dockerfile, build/build.sh, component-samples/demo/aio/Dockerfile, component-samples/demo/device/Dockerfile, component-samples/demo/manufacturer/Dockerfile, component-samples/demo/owner/Dockerfile, component-samples/demo/reseller/Dockerfile, component-samples/demo/rv/Dockerfile
=> Adding support for Java 17

README.md, build/Podmanfile, component-samples/demo/README.MD, component-samples/demo/aio/Podmanfile, component-samples/demo/aio/README.md, component-samples/demo/device/Podmanfile, component-samples/demo/manufacturer/Podmanfile, component-samples/demo/manufacturer/README.md, component-samples/demo/owner/Podmanfile, component-samples/demo/owner/README.md, component-samples/demo/reseller/Podmanfile, component-samples/demo/reseller/README.md, component-samples/demo/rv/Podmanfile, component-samples/demo/rv/README.md
Migrate PodmanFiles from Java 11 to Java 17.
=> Migrate PodmanFiles from Java 11 to Java 17

README.md, component-samples/demo/scripts/keys_gen.sh
Updating keys_gen.sh script to clean api-user.pem
=> Updating keys_gen.sh script

component-samples/aio/pom.xml, component-samples/device/pom.xml, pom.xml, protocol/pom.xml
Upgrading dependencies to the latest version.
=> Upgrading dependencies to the latest version

component-samples/device/src/main/java/org/fidoalliance/fdo/sample/DeviceApp.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/HttpClient.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/StandardMessageDispatcher.java
Refactoring logs of DeviceApp.
=> Refactoring logs of DeviceApp

component-samples/demo/README.MD, component-samples/demo/aio/Dockerfile-slim, component-samples/demo/manufacturer/Dockerfile-slim, component-samples/demo/owner/Dockerfile-slim, component-samples/demo/reseller/Dockerfile-slim, component-samples/demo/rv/Dockerfile-slim
Upgrading docker slim image to Java 17.
=> Upgrading docker slim image to Java 17

README.md, component-samples/demo/scripts/enable_podman_support.sh
=> Fixing RHEL build script

build/enable_podman_support.sh, component-samples/demo/README.MD
Updating build script for RHEL.
=> Updating build script for RHEL

build/README.md
=> Updating RHEL Build README

component-samples/aio/pom.xml, component-samples/demo/aio/service.yml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/service.yml, component-samples/demo/reseller/service.yml, component-samples/demo/rv/service.yml, component-samples/device/pom.xml, component-samples/pom.xml, pom.xml, protocol/pom.xml
Version rollover to 1.1.6 Release.
=> Version rollover to 1.1.6 Release

component-samples/demo/aio/Dockerfile, component-samples/demo/device/Dockerfile, component-samples/demo/manufacturer/Dockerfile, component-samples/demo/owner/Dockerfile, component-samples/demo/reseller/Dockerfile, component-samples/demo/rv/Dockerfile
=> Fixing Trivy scan reports

build/Dockerfile
=> Trivy fix on build script

component-samples/demo/aio/WEB-INF/web.xml, component-samples/demo/device/README.md, component-samples/demo/device/service.yml, component-samples/demo/manufacturer/WEB-INF/web.xml
=> Enable mTLS support for DI

protocol/src/main/java/org/fidoalliance/fdo/protocol/StandardMessageDispatcher.java
This fixes - [SDOPT-13342](https://jira.devtools.intel.com/browse/SDOPT-13342)
Overview : Added input validation for request message
=> [Fixed] Msg20 in TO0 accepts invalid values within message body

protocol/src/main/java/org/fidoalliance/fdo/protocol/HttpClient.java
Add logging for failed TO0 when all RVInfo are invalid.
=> Add logging for failed TO0 when all RVInfo are invalid 

protocol/src/main/java/org/fidoalliance/fdo/protocol/db/AutoInjectVoucherStorageFunction.java
Updating the voucher expiry timeline for AutoInjection Worker.
=> Updating the voucher expiry timeline for AutoInjection Worker

protocol/src/main/java/org/fidoalliance/fdo/protocol/VoucherUtils.java
Enabling voucher extension with different device
attestion type and Owner key type.
=> Enabling cross device attestation

component-samples/demo/reseller/service.yml
Changing the default reseller keystore filename.
=> Changing the default reseller keystore filename

component-samples/demo/scripts/package/build-package.sh, component-samples/demo/scripts/package/onboard-device.sh, component-samples/demo/scripts/package/post-service-info.sh, component-samples/demo/scripts/package/run-health-check.sh, component-samples/demo/scripts/package/svi-insructions.txt, component-samples/demo/scripts/package/upload-resource.sh, protocol/src/main/java/org/fidoalliance/fdo/protocol/api/To0Starter.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/db/FdoSysModuleExtra.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/db/FdoSysOwnerModule.java
FdoSys Module fetch will upload files to app-data/<device-guid>/<fetch filename>
demo/scripts/package as scripts for creating a demo-package.tar.gz, uploading it to owner, and provide svi for processing it
TO0Started updated to allow serialno as well as GUID
=> updated fetch to the app-data directory and added svi packaging

component-samples/demo/README.MD
Updated Owner exec docs to add message to customize the packages in dockerfile
=> Updated Owner exec docs 

component-samples/device/src/main/java/org/fidoalliance/fdo/sample/FdoSimDownloadDeviceModule.java, component-samples/device/src/main/java/org/fidoalliance/fdo/sample/FdoSimWebGetDeviceModule.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/StandardMessageDispatcher.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/api/To2Blob.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/db/FdoSimCommandOwnerModule.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/db/FdoSimCsrOwnerModule.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/db/FdoSimDownloadOwnerModule.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/db/FdoSimUploadOwnerModule.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/db/FdoSimWebGetOwnerModule.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/db/FdoSysOwnerModule.java
Coverity Fixes for 1.1.7 Release.
=> Coverity Fixes for 1.1.7 Release

README.md, build/README.md, component-samples/demo/README.MD, component-samples/demo/scripts/package/build-package.sh
Updating README with RHEL OS version and fixing typos
=> Updating README with RHEL OS version and fixing typos

README.md, component-samples/demo/aio/README.md
=> Updating filter README

component-samples/aio/pom.xml, component-samples/demo/aio/service.yml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/service.yml, component-samples/demo/reseller/service.yml, component-samples/demo/rv/service.yml, component-samples/device/pom.xml, component-samples/pom.xml, pom.xml, protocol/pom.xml
Version rollover to 1.1.7 Release.
=> Version rollover to 1.1.7 Release

component-samples/device/src/main/java/org/fidoalliance/fdo/sample/FdoSimCommandDeviceModule.java
Fixing multiple script execution in FSIM.
=> Fixing multiple script execution in FSIM

component-samples/demo/scripts/fdorvconfig.sh
Adding script to configure AIO and Owner components for hosted RV instance.
=> Adding script to configure AIO and Owner components for hosted RV

pom.xml
Upgraded versions of various dependencies and maven in pom.xml file
=> Upgraded versions of various dependencies and maven in pom.xml file

component-samples/demo/aio/WEB-INF/web.xml, component-samples/demo/owner/WEB-INF/web.xml, protocol/src/main/java/org/fidoalliance/fdo/protocol/api/RvReplacementApi.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/db/StandardVoucherReplacementFunction.java
Adding REST endpoints to support Replacement RVInfo.
=> Adding REST endpoints to support Replacement RVInfo

pom.xml, protocol/src/main/java/org/fidoalliance/fdo/protocol/OnDieCertSignatureFunction.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/StandardCryptoService.java
Coverity Fixes for 1.1.8 Release.
=> Coverity Fixes for 1.1.8 Release

protocol/src/main/java/org/fidoalliance/fdo/protocol/db/FdoSimDownloadOwnerModule.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/db/FdoSysModuleExtra.java
Fixing multiple file download for FSIM_Download Module.
=> Fixing multiple file download for FSIM_Download Module

protocol/src/main/java/org/fidoalliance/fdo/protocol/HttpClient.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/HttpUtils.java
Adding delay in connection when RVDelay parameter is set in RVInfo.
=> Adding delay in connection when RVDelay parameter is set in RVInfo

protocol/src/main/java/org/fidoalliance/fdo/protocol/OnDieCertSignatureFunction.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/PemFormatter.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/StandardCryptoService.java
Security fixes based on static analysis.
=> Security fixes based on static analysis

README.md
=> Adding FIPS notice to README

component-samples/aio/pom.xml, component-samples/demo/aio/service.yml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/service.yml, component-samples/demo/reseller/service.yml, component-samples/demo/rv/service.yml, component-samples/device/pom.xml, component-samples/pom.xml, pom.xml, protocol/pom.xml
Version rollover to 1.1.8 Release.
=> Version rollover to 1.1.8 Release

component-samples/demo/aio/WEB-INF/web.xml, component-samples/demo/manufacturer/WEB-INF/web.xml, protocol/src/main/java/org/fidoalliance/fdo/protocol/StandardMessageDispatcher.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/api/MacAddress.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/db/ManufacturingInfoStorageFunction.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/entity/ManufacturedVoucher.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/message/ManufacturingInfo.java, protocol/src/main/java/org/fidoalliance/fdo/protocol/serialization/ManufacturingInfoDeserializer.java
Add support to parse and load device MAC addresses from Device Mfg Info
=> Add support to parse and load device MAC addresses from Device MfgInfo

component-samples/demo/db/docker-compose.yml
Db fix version to last working version to 11.4.2
=> Db fix version to last working version to 11.4.2

component-samples/aio/pom.xml, component-samples/demo/aio/service.yml, component-samples/demo/manufacturer/service.yml, component-samples/demo/owner/service.yml, component-samples/demo/reseller/service.yml, component-samples/demo/rv/service.yml, component-samples/device/pom.xml, component-samples/pom.xml, pom.xml, protocol/pom.xml
Version rollover to 1.1.9 Release.
=> Version rollover to 1.1.9 Release

.github/workflows/release.yaml, release/notes/release-notes-v1.1.10.md
Example release: https://github.com/kroczi/pri-fidoiot/releases/tag/v1.1.10
Build: https://github.com/kroczi/pri-fidoiot/actions/runs/16848951035
=> Add release pipeline and release notes for v1.1.10
