fido-device-onboard/pri-fidoiot

- cert-utils/pom.xml
- pom.xml
- protocol/pom.xml
- service/http-client-samples/http-client-di-sample/pom.xml
- service/http-client-samples/http-client-to0-sample/pom.xml
- service/http-client-samples/http-client-to1-sample/pom.xml
- service/http-client-samples/http-client-to2-sample/pom.xml
- service/http-client-samples/pom.xml
- service/http-dispatchers/http-client-dispatcher/pom.xml
- service/http-dispatchers/http-server-dispatcher/pom.xml
- service/http-dispatchers/pom.xml
- service/http-server-samples/http-server-di-sample/pom.xml
- service/http-server-samples/http-server-owner-sample/pom.xml
- service/http-server-samples/http-server-rv-sample/pom.xml
- service/http-server-samples/pom.xml
- service/pom.xml
- storage/pom.xml
- storage/storage-samples/pom.xml
- storage/storage-samples/storage-di-sample/pom.xml
- storage/storage-samples/storage-owner-sample/pom.xml
- storage/storage-samples/storage-rv-sample/pom.xml
This is the third development cycle for new protocol (known as FIDO-IoT
going forward). The previous 2 TAGs can be considered as 0.1 and 0.2
release and this release can be considered as 0.3 release of the
preliminary implementation.
The version is rolled to 0.3-SNAPSHOT to enable development for this
cycle.
> Roll version for 0.3 development

- cert-utils/src/main/java/org/fido/iot/certutils/PemLoader.java
OpenSSL is a common tool and we should be able to read PEM
files generated from it.
> Add support for openssl types to PemLoader

- protocol/src/main/java/org/fido/iot/protocol/CryptoService.java
- protocol/src/main/java/org/fido/iot/protocol/To0ClientService.java
- protocol/src/main/java/org/fido/iot/protocol/To1ClientService.java
- protocol/src/main/java/org/fido/iot/protocol/To2ClientService.java
- protocol/src/main/java/org/fido/iot/protocol/To2ServerService.java
- protocol/src/main/java/org/fido/iot/protocol/VoucherExtensionService.java
- protocol/src/test/java/org/fido/iot/protocol/Ec256Test.java
- protocol/src/test/java/org/fido/iot/protocol/Ec384Test.java
Updating the sign() method's argument list by adding the COSE signature
algorithm to be used, instead of determining the same inside the method.
This enables us to use public key to determine the field-size/
modulus-bit-length for EC and RSA keys.
> Add COSE algorithm id to sign method argument list

- protocol/src/main/java/org/fido/iot/protocol/To2ClientService.java
- protocol/src/main/java/org/fido/iot/protocol/To2ClientStorage.java
- protocol/src/main/java/org/fido/iot/protocol/To2ServerService.java
- protocol/src/test/java/org/fido/iot/protocol/To2Test.java
- service/http-client-samples/http-client-to2-sample/src/main/java/org/fido/iot/web/To2ClientApp.java
- storage/storage-samples/storage-owner-sample/src/test/java/org/fido/iot/storage/To2StorageTest.java
Storage client updates credentials and checks for credential re-use protocol.
Client has choice to support re-use by returning null for the replacement HMAC
or to go ahead and return a new HMAC.
> Added storage call to get HMAC replacement key and update credentials

- storage/storage-samples/storage-di-sample/src/main/java/org/fido/iot/storage/DiDbManager.java
It is most common for owner and device rendezvous ports to be identical.
Letting the owner-port default to 80 causes the PRI to fail in TO0.
Include the owner port in the default rendezvous so the PRI will work
out of the box.
> Add owner port to default rendezvous

- protocol/pom.xml
- protocol/src/main/java/org/fido/iot/protocol/Const.java
- protocol/src/main/java/org/fido/iot/protocol/CryptoService.java
When EC parameter field toString() is called on bouncycastle
ECNamedCurveSpec objects, it produces a java-style "class@address"
string, which is not what we want.
Instead, fetch and test the curve name field from the parameter
spec object if it's a bouncycastle object.
Accept the legacy name for secp256r1: prime256v1.
> Fix: fetch the correct EC curve name when verifying

- protocol/src/main/java/org/fido/iot/protocol/Const.java
- protocol/src/main/java/org/fido/iot/protocol/CryptoService.java
- MAROE Prefix verification added for msg/32 and msg/64 for
EPID devices.
- Added verifyMaroePrefix function in cryptoService class.
> Adding MAROE Prefix verification.

- service/component-samples/http-device-sample/pom.xml
This allows the JAR to be executed via 'java -jar'.
> Fix: add classpath to executable JAR

- demo/owner/owner.env
- demo/rv/rv.env
- protocol/src/main/java/org/fido/iot/protocol/epid/EpidUtils.java
- service/component-samples/owner/src/main/java/org/fido/iot/sample/OwnerAppConstants.java
- service/component-samples/owner/src/main/java/org/fido/iot/sample/OwnerConfigLoader.java
- service/component-samples/owner/src/main/java/org/fido/iot/sample/OwnerContextListener.java
- service/component-samples/owner/src/main/java/org/fido/iot/sample/OwnerServerApp.java
- service/component-samples/rv/src/main/java/org/fido/iot/sample/RvAppSettings.java
- service/component-samples/rv/src/main/java/org/fido/iot/sample/RvConfigLoader.java
- service/component-samples/rv/src/main/java/org/fido/iot/sample/RvContextListener.java
- service/component-samples/rv/src/main/java/org/fido/iot/sample/RvServerApp.java
- Added EPID URL config property to Component sample Owner and Rv apps.
- Additonally, updating config loaders to return null instead of
throwing exception, in case property is not found.
> Adding epid url config property at component samples

- demo/owner/owner.env
- service/component-samples/owner/src/main/java/org/fido/iot/sample/OwnerAppConstants.java
- service/component-samples/owner/src/main/java/org/fido/iot/sample/OwnerContextListener.java
- service/component-samples/owner/src/main/java/org/fido/iot/sample/OwnerServerApp.java
- service/component-samples/owner/src/main/java/org/fido/iot/sample/OwnerTo0Client.java
- storage/storage-samples/storage-owner-sample/src/main/java/org/fido/iot/storage/OwnerDbTo0Storage.java
- storage/storage-samples/storage-owner-sample/src/main/java/org/fido/iot/storage/OwnerDbTo0Util.java
- Eligible devices for TO0 (based on their stored TO0 wait seconds) are
scheduled on a separate thread, managed by ExecutorService.
- Moved To0ClientStorage impl to Owner storage and updated TO0Client
appropriately.
- Added few configurable properties to manage scheduling TO0 and removed
few hard-coded values from TO0Client.
Additionally, fixed whitespacing issues at places.
> Update handling of To0Client of Component Owner

- protocol/src/main/java/org/fido/iot/protocol/epid/EpidSignatureVerifier.java
- service/component-samples/http-device-sample/src/main/java/org/fido/iot/sample/Device.java
- service/component-samples/manufacturer/src/main/java/org/fido/iot/sample/ManufacturerConfigLoader.java
- service/component-samples/owner/src/main/java/org/fido/iot/sample/OwnerConfigLoader.java
- service/component-samples/rv/src/main/java/org/fido/iot/sample/RvConfigLoader.java
- storage/storage-samples/storage-di-sample/src/main/java/org/fido/iot/storage/DiDbStorage.java
1. In DiDbStorage.java, removing the unused variable **'SubjectPublicKey'**
2. In EpidSignatureVerifer.java, **Adding null check on 'signedPayload'** to
avoid dereferencing which may result in nullpointer exception.
3. In Device.java, **Adding null check on 'credentials'** to
avoid dereferencing which may result in nullpointer exception.
4. In Owner,RV,ManufacturerConfigLoader.java, **resolving the empty catch
clause** issue by printing an error message.
> Resolving klocwork issues

- protocol/src/main/java/org/fido/iot/protocol/To2ClientService.java
Following updates as per the spec.
- To2ClientService currently sends null to owner, in case reuse is selected.
Updating it to send CBOR null instead, as per the protcol spec.
Also, the GUID and RendezvousInfo comparison was being done using
voucher's creds, instead of comparing voucher's creds against the
received contents in type 65. Updated the same.
- Fixing an issue where during TO2, To2Client wasn't requesting for the
OVEntries correctly, by skipping the last entry altogether. For example,
for sz=1, OVEntry[0] isn't requested.
> Updating as per spec, reuse and OVEntry handling at To2ClientService

- protocol/src/main/java/org/fido/iot/protocol/CryptoService.java
- service/component-samples/http-device-sample/pom.xml
- Updated cryptoservice to handle empty composite object
sent by HTTP device component sample for 'eA' field for
non-EPID devices.
> Fix for HTTP Device Component sample.

- service/component-samples/manufacturer/src/main/java/org/fido/iot/sample/ManufacturerApp.java
- service/component-samples/owner/src/main/java/org/fido/iot/sample/OwnerServerApp.java
- service/component-samples/reseller/src/main/java/org/fido/iot/sample/ResellerServerApp.java
- service/component-samples/rv/src/main/java/org/fido/iot/sample/RvServerApp.java
- service/protocol-samples/http-server-di-sample/src/main/java/org/fido/iot/sample/DiApp.java
- service/protocol-samples/http-server-to0-to1-sample/src/main/java/org/fido/iot/sample/To0To1ServerApp.java
- service/protocol-samples/http-server-to2-sample/src/main/java/org/fido/iot/sample/To2ServerApp.java
- Properties `webAllowOthers` and `tcpAllowOthers` allow remote connections to the DB,
While doing so they create a security hole in the system. Not recommended to use on
production system. So remote connection to DB has been made disabled by
default.
> Making remote DB connection to DB disabled by default.

- README.md
- demo/README.md
- demo/device/README.md
- demo/manufacturer/README.md
- demo/owner/README.md
- demo/reseller/README.md
- demo/rv/README.md
All Component Sample related demo instructions are moved in the READMEs inside Demo folder. Top level README contains steps to perform demo using protocol samples and a link to Demo README for Component samples demo.
Added instructions to perform allowlist and denylist operations on RV component sample.
Added new APIs to the respective component REST contract.
Added instructions to enable remote access to DB.
Includes fix for github issues 74-79 and semantic fixes after proofread.
> README Update

- protocol/src/main/java/org/fido/iot/protocol/To2ClientService.java
- protocol/src/main/java/org/fido/iot/protocol/To2ServerService.java
- Updating the To0ClientService.doSetupDevice() to use the owner-sent
credentials to calculate hmac, in case resale protocol has been enabled.
- Updating the To2ServerService.doDone() to convert the input hmac to
Composite before setting it into the new voucher.
> Updating for resale protocol in protocol To2 Client & Server services

- demo/rv/rv.env
- service/component-samples/rv/src/main/java/org/fido/iot/sample/RvAppSettings.java
- service/component-samples/rv/src/main/java/org/fido/iot/sample/RvContextListener.java
- service/component-samples/rv/src/main/java/org/fido/iot/sample/RvServerApp.java
Making EPID test mode configurable in RV component sample to
allow ease in toggling.
> rv: Add option to set test mode for EPID

- service/component-samples/owner/src/main/java/org/fido/iot/sample/OwnerServerApp.java
- service/http-api-samples/http-api-owner-sample/src/main/java/org/fido/iot/api/OwnerSetupInfoServlet.java
- storage/storage-samples/storage-owner-sample/src/main/java/org/fido/iot/storage/OwnerDbManager.java
- Added an API that updates the Device Setup info (replacement GUID,
RVInfo). Request body is off the form:
guid:=<guid>,rvinfo:=<rvinfo>
where ':=' is value delimeter (= is used in RVInfo) and ',' is array delimeter.
> Owner API Addition: API to update Device setupinfo

- service/component-samples/manufacturer/src/main/java/org/fido/iot/sample/ManufacturerContextListener.java
- service/component-samples/reseller/src/main/java/org/fido/iot/sample/ResellerContextListener.java
- Added the default reseller keys into component manufacturer. The same
keys are present in Reseller's keystore at /demo/reseller/reseller_keystore.p12
- Added the default owner keys into component reseller. The same keys
are present in Owner's keystore at /demo/owner/owner_keystore.p12
> Adding default Reseller and owner keys at component samples

- protocol/src/main/java/org/fido/iot/protocol/epid/EpidMaterialService.java
- service/component-samples/reseller/src/main/java/org/fido/iot/sample/ResellerConfigLoader.java
- service/component-samples/reseller/src/main/java/org/fido/iot/sample/ResellerDbManager.java
1.In ResellerDbManager, Removing guid variable as it is never
read after being assigned.
2.In EpidMaterialService, Removing certRequestInfo variable as it is never
read after being assigned.
3.In ResellerConfigLoader, resolving the empty catch
clause issue by printing an error message.
4.In EpidMaterialService, resolving the empty catch
clause issue by printing an error message.
> Fixing the Klocwork issues

- demo/owner/owner-entrypoint.sh
Adding argument to configure heap size in owner entrypoint script.
Some heap size issues are observed in the service as the H2 DB size
grows, this can be resolved by increasing heap size. To troubleshoot
any issues encountered due to service heap size, update the it in 
`demo/owner-entrypoint.sh` script. Default is 256MB.
> [Fix][component-samples] Owner service heap size configuration.

- service/component-samples/http-device-sample/src/main/java/org/fido/iot/sample/Device.java
- serviceinfo/src/main/java/org/fido/iot/serviceinfo/ServiceInfoEntry.java
- serviceinfo/src/main/java/org/fido/iot/serviceinfo/ServiceInfoMarshaller.java
- storage/storage-samples/storage-owner-sample/src/main/java/org/fido/iot/storage/OwnerDbManager.java
- storage/storage-samples/storage-owner-sample/src/main/java/org/fido/iot/storage/OwnerDbStorage.java
- storage/storage-samples/storage-owner-sample/src/main/java/org/fido/iot/storage/OwnerServiceInfoSequence.java
- The earlier approach created the servieinfo messages from the start
index until the service info that the Owner wishes to send was found,
while iterating over it. This meant that more the number of serviceinfo
messages to be sent, the longer it took to iterate and find the message
owner needed to send.
- In the current approach that fixes the issue, the
'ServiceinfoMarshaller' is serialized/de-serialized to-and-from
database. This allows the Owner to directly find the message and send,
since the Marshaller state is stored, and the iteration to create
messages is completely avoided.
- Additionally, fixing an issue with the Device wherin it sent the same
DeviceServiceinfo message in Type 68 again and again to the owner.
> Fixing the slow nature of Service info transfer

- service/protocol-samples/http-client-to2-sample/src/main/java/org/fido/iot/sample/To2ClientApp.java
- Fixed an issue where TO2 was being done for all URLs in the RV blob,
regardless of the previous TO2 result.
> Fix an issue with TO2Client protocol sample

- protocol/pom.xml
- service/component-samples/manufacturer/pom.xml
- service/component-samples/owner/pom.xml
- service/component-samples/reseller/pom.xml
- service/component-samples/rv/pom.xml
- service/http-api-samples/http-api-di-sample/pom.xml
- service/http-api-samples/http-api-keystore-sample/pom.xml
- service/http-api-samples/http-api-owner-sample/pom.xml
- service/http-api-samples/http-api-rv-sample/pom.xml
- service/http-dispatchers/http-client-dispatcher/pom.xml
- service/http-dispatchers/http-server-dispatcher/pom.xml
- service/protocol-samples/http-client-di-sample/pom.xml
- service/protocol-samples/http-client-to0-sample/pom.xml
- service/protocol-samples/http-client-to1-sample/pom.xml
- service/protocol-samples/http-client-to2-sample/pom.xml
- service/protocol-samples/http-server-di-sample/pom.xml
- service/protocol-samples/http-server-to0-to1-sample/pom.xml
- service/protocol-samples/http-server-to2-sample/pom.xml
- storage/storage-samples/storage-di-sample/pom.xml
- storage/storage-samples/storage-owner-sample/pom.xml
- storage/storage-samples/storage-rv-sample/pom.xml
Updated tomcat version to 9.0.40 to fix known vulnerability
CVE-2020-17527.
> Update tomcat version to 9.0.40

- README.md
- protocol/src/main/java/org/fido/iot/protocol/Const.java
- protocol/src/main/java/org/fido/iot/protocol/RendezvousInfoDecoder.java
- protocol/src/main/java/org/fido/iot/protocol/To2ClientService.java
- service/component-samples/http-device-sample/src/main/java/org/fido/iot/sample/Device.java
Adding RVBypass support for PRI-device.
RVBypass Scenario:
1. When RVBypass flag is set in RVinfo;
the client skips T01 and proceeds with T02.
2. And during T02, the client skips Rendezvous blob
verification.
> Adding RVBypass support for PRI-device

- protocol/src/main/java/org/fido/iot/protocol/cbor/Decoder.java
In certain scenarios, when major type value length is same as the
AdditionalInfo Indefinite length, the decoder was incorrectly
throwing an unsupported operation exception. This fix resolves
the bug in such a corner case issue.
> [Fix] Decoder fix

- protocol/src/main/java/org/fido/iot/protocol/Const.java
- protocol/src/main/java/org/fido/iot/protocol/CryptoService.java
The KDF used in the PRI does not match that
defined by the spec in sections 3.7.1.x.
Update it to match.
> Update KDF to match spec

- util/cert-utils/src/test/java/org/fido/iot/certutils/CertTest.java
- util/cert-utils/src/test/java/org/fido/iot/certutils/PrivateKeyTest.java
- util/cert-utils/src/test/java/org/fido/iot/certutils/PublicKeyTest.java
Adding unit tests to cert-utils.
New unit test covers:
All exception handling structures.
Functional test on loadPrivateKey() method.
> Adding unit tests to cert-utils

- component-samples/manufacturer/src/main/java/org/fido/iot/sample/ManufacturerContextListener.java
PRI Manufacturer was picking up EC256 certificate for the issuer certchain
while creating device ownership voucher for both EC256 and EC384 device
key types. This was resulting in onboarding failure during TO2 due to hash mismatch.
This was happening because in the Manufacturer Storage method `getCertChain`,
only the key algorithm was being checked, which is `ECDH` for both EC256 and EC384
keytypes.
To resolve this issue, an additional check has been added to the
function and the keytype check has been added on top of existing checks
to retrieve the expected certificate.
> Fixing EC384 support

- component-samples/reseller/src/main/java/org/fidoalliance/fdo/sample/ResellerCustomerServlet.java
- component-samples/reseller/src/main/java/org/fidoalliance/fdo/sample/ResellerDbManager.java
DELETE API call on reseller/voucher/* was returning
200 OK, even when there is no item to be deleted. So fixing 
endpoints to return Status 404 when items are not present.
> Fixing reseller/voucher/* api endpoints

- protocol/src/main/java/org/fidoalliance/fdo/protocol/To2ClientService.java
Refactoring minimum MTU logging conditions. Previously,
even for zero device.mtu.size , the device logged Negative values 
received. So fixing the check conditions for more accurate logging.
> Refactoring minimum MTU logging conditions

- component-samples/reseller/src/main/java/org/fidoalliance/fdo/sample/ResellerCustomerServlet.java
Adding the following input sanity check to reseller/voucher endpoint
- whether id is an empty or valid positive number
- Whether customer_name is empty
- Whether PEM body is in a valid format.
> Adding input sanity check on reseller/voucher endpoint

- protocol/src/main/java/org/fidoalliance/fdo/protocol/To2ClientService.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/To2ServerService.java
When mtu size is set to zero or negative value in the TO2_SETTINGS
table, TO2 fails with msg/66 giving a null pointer exception.
> Fixing issue with variable mtu.

- component-samples/http-device-sample/pom.xml
- component-samples/manufacturer/pom.xml
- component-samples/owner/pom.xml
- component-samples/reseller/pom.xml
- component-samples/rv/pom.xml
- http-api-samples/http-api-di-sample/pom.xml
- http-api-samples/http-api-keystore-sample/pom.xml
- http-api-samples/http-api-owner-sample/pom.xml
- http-api-samples/http-api-rv-sample/pom.xml
- pom.xml
- protocol-samples/http-client-di-sample/pom.xml
- protocol-samples/http-client-to0-sample/pom.xml
- protocol-samples/http-client-to1-sample/pom.xml
- protocol-samples/http-client-to2-sample/pom.xml
- protocol-samples/http-server-di-sample/pom.xml
- protocol-samples/http-server-to0-to1-sample/pom.xml
- protocol-samples/http-server-to2-sample/pom.xml
- protocol/pom.xml
- util/http-dispatchers/http-client-dispatcher/pom.xml
- util/http-dispatchers/http-server-dispatcher/pom.xml
- util/storage-samples/storage-di-sample/pom.xml
- util/storage-samples/storage-owner-sample/pom.xml
- util/storage-samples/storage-rv-sample/pom.xml
The version of following dependencies were updated.
- commons-codec from 1.14 -> 1.15
- commons-dbcp2 from 2.7.0 -> 2.8.0
- junit-jupiter from 5.6.1 -> 5.7.1
- log4j from 2.13.3 -> 2.14.1
- tomcat from 9.0.44 -> 9.0.45
> Update the version of third-party dependencies

- protocol/src/main/java/org/fidoalliance/fdo/protocol/To1ServerService.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/To1ServerStorage.java
- protocol/src/test/java/org/fidoalliance/fdo/protocol/To1Test.java
- util/storage-samples/storage-rv-sample/src/main/java/org/fidoalliance/fdo/storage/To0AllowListDenyListDbStorage.java
- util/storage-samples/storage-rv-sample/src/main/java/org/fidoalliance/fdo/storage/To0DbStorage.java
- util/storage-samples/storage-rv-sample/src/main/java/org/fidoalliance/fdo/storage/To1DbStorage.java
The Rendezvous Server should associate GUID with the new owner’s
address information for To0.AcceptOwner.WaitSeconds seconds. Adding
check for the same in To1 Server Service.
> Adding check for To0 WaitSeconds in To1 Server.

- util/storage-samples/storage-owner-sample/src/main/java/org/fidoalliance/fdo/storage/OwnerSysModule.java
This is done to prevent overflow of certain DAL devices
> adjust max read for filewrite

- Jenkinsfile.yml
Updating the TO0 scheduling time interval from 300 to 30 seconds.
> Updating the TO0 scheduling time interval in Jenkinsfile

- protocol/src/main/java/org/fidoalliance/fdo/protocol/CryptoService.java
> Use bits, not bytes, for L in KDF

- protocol/src/main/java/org/fidoalliance/fdo/protocol/CryptoService.java
> Use a 12-byte IV for GCM

- component-samples/demo/README.md
- component-samples/scripts/onDieCache.py
- protocol/src/main/java/org/fidoalliance/fdo/protocol/ondie/OnDieCache.java
- Fix to download ondie .crts and .crls into the path specified by
ondie_cache variable. Previously .crts and .crls were
downloaded into the _JAVA_EXECUTION_PATH instead of the
path specified by ondie_cache variable.
- Fix to strip .new extension from the .crts and .crls files
downloaded through onDieCache.py script.
> Fixing ondie path issues

- component-samples/aio/src/main/java/org/fidoalliance/fdo/sample/AioCertificateResolver.java
- component-samples/aio/src/main/java/org/fidoalliance/fdo/sample/AioConfigLoader.java
- component-samples/aio/src/main/java/org/fidoalliance/fdo/sample/AioContextListener.java
- component-samples/aio/src/main/java/org/fidoalliance/fdo/sample/AioOwnerKeyResolver.java
- component-samples/demo/device/log4j2.xml
- component-samples/demo/manufacturer/log4j2.xml
- component-samples/demo/owner/log4j2.xml
- component-samples/demo/reseller/log4j2.xml
- component-samples/demo/rv/log4j2.xml
- component-samples/manufacturer/src/main/java/org/fidoalliance/fdo/sample/ManufacturerContextListener.java
- component-samples/owner/src/main/java/org/fidoalliance/fdo/sample/OwnerContextListener.java
- component-samples/reseller/src/main/java/org/fidoalliance/fdo/sample/ResellerContextListener.java
- component-samples/rv/src/main/java/org/fidoalliance/fdo/sample/RvContextListener.java
- http-api-samples/http-api-di-sample/src/main/java/org/fidoalliance/fdo/api/RvInfoServlet.java
- protocol-samples/http-server-di-sample/src/main/java/org/fidoalliance/fdo/sample/DiContextListener.java
- protocol-samples/http-server-to0-to1-sample/src/main/java/org/fidoalliance/fdo/sample/To0To1ContextListener.java
- protocol-samples/http-server-to2-sample/src/main/java/org/fidoalliance/fdo/sample/To2ContextListener.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/RendezvousInfoDecoder.java
- util/http-dispatchers/http-client-dispatcher/src/main/java/org/fidoalliance/fdo/sample/WebClient.java
- util/storage-samples/storage-owner-sample/src/main/java/org/fidoalliance/fdo/storage/OwnerTestModule.java
Include the message number while logging the protocol messages. This
would improve debugging capabilities.
In current implementation, the logging was enabled only for Services.
This is now extended for the Clients too (to0Client and Device).
In future, this would also help to prepare some analytics tool that can
parse the log message and create more useful information.
> Add msgid in protocol message logs

- util/serviceinfo/src/main/java/org/fidoalliance/fdo/serviceinfo/ModuleManager.java
- util/storage-samples/storage-owner-sample/src/main/java/org/fidoalliance/fdo/storage/OwnerSysModule.java
- Fix an issue where the 'fdo_sys:active=false' was not sent to the
device.
- Fix an issue where empty ServiceInfo was being sent as [[[]]], instead
of [].
- Fix an issue where OwnerSysModule was always returning 'false' at
isMore(), by aligning hasMore()'s return with isMore().
> Fix some minor issues with serviceinfo

- component-samples/aio/pom.xml
- component-samples/aio/src/main/java/org/fidoalliance/fdo/sample/AioDbManager.java
- component-samples/aio/src/main/java/org/fidoalliance/fdo/sample/AioInfoServlet.java
- component-samples/aio/src/main/java/org/fidoalliance/fdo/sample/AioServerApp.java
- component-samples/demo/aio/README.md
- pom.xml
Implements a REST end-point to for serving additional device information from
AIO. The REST end-point extracts following information from the database.
- SerialNumber
- Timestamp for DI
- Device GUID
and serves this information through /api/v1/deviceinfo/* REST
endpoints.
> Implements a REST endpoint in AIO for Serving Device Info

- component-samples/demo/owner/owner.env
The TO0 scheduler time was changed from 300s to 10s by mistake,
reverting back to original value.
> Revert TO0 scheduler interval to 300s

- component-samples/demo/rv/rv.env
- util/http-dispatchers/http-server-dispatcher/src/test/java/org/fidoalliance/fdo/sample/ServletTest.java
- util/storage-samples/storage-di-sample/src/main/java/org/fidoalliance/fdo/storage/DiDbManager.java
- util/storage-samples/storage-di-sample/src/test/java/org/fidoalliance/fdo/storage/DiStorageTest.java
- util/storage-samples/storage-owner-sample/src/test/java/org/fidoalliance/fdo/storage/To2StorageTest.java
- util/storage-samples/storage-rv-sample/src/test/java/org/fidoalliance/fdo/storage/RvsStorageTest.java
8443 is used by RV and AIO services. Changed RV service to use 8041
as HTTPS port.
8043 is used by Owner Service as HTTPS port and also in the unit test.
Changed the unit test to use 8091.
8040 is used by RV Service as HTTP port and also in the unit test. Changed
the unit test to 8090 as test port.
> Use non-default demo port for unit-test

- http-api-samples/http-api-owner-sample/src/main/java/org/fidoalliance/fdo/api/OwnerSetupInfoServlet.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/Debug.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/To2ServerService.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/To2ServerStorage.java
- util/storage-samples/storage-owner-sample/src/main/java/org/fidoalliance/fdo/storage/OwnerDbStorage.java
Add a flag, Debug.IS_REUSE_DISABLED, which controls reuse
in the owner.  By default, reuse is disabled and replacement
GUIDs are auto-generated.
> Disable credential reuse in the owner

- Jenkinsfile.yml
- component-samples/demo/aio/aio.env
- component-samples/demo/manufacturer/manufacturer.env
- component-samples/demo/owner/owner.env
- component-samples/demo/reseller/reseller.env
- component-samples/demo/scripts/keys_gen.sh
- component-samples/reseller/src/main/java/org/fidoalliance/fdo/sample/ResellerServerApp.java
Updated the keys_gen.sh script to generate the API password during
runtime. The component env files are updated to remove the password for
API access.
While at it, reseller component is updated to take the username from
environment variable.
> Auto-generate API password

- component-samples/owner/src/main/java/org/fidoalliance/fdo/sample/OwnerTo0Client.java
- Fix an issue where exception was being thrown on any exception,
except ConnectException, causing the Owner to not iterate through all
the RV locations. Instead, the exception will now be thron only if all
the RV locations have been tried once and failed.
> Error out on TO0 after entire RVInfo is tried

- component-samples/demo/manufacturer/manufacturer.env
Enabling TLS by default in manufacturer.
> Enabling TLS by default in manufacturer

- component-samples/demo/README.md
- component-samples/demo/aio/aio.env
- component-samples/demo/manufacturer/Dockerfile
- component-samples/demo/manufacturer/manufacturer.env
- component-samples/demo/owner/Dockerfile
- component-samples/demo/owner/owner.env
- component-samples/demo/scripts/onDieCache.py
Update the example configurations for on-prem setup.
In order to enable OnDie support, the script 'onDieCache.py' needs to be
run before starting the docker container to populate the ondie_cache
directory.
> Update OnDie Cache configurations

- build/build.sh
The PGP signature verification requires additional proxy configuration in
~/.m2/settings.xml. For simplicity and easier out of box experience, the PGP
signature verification is disabled here. In case this is used to create
production build, it is recommended to update ~/.m2/settings.xml to include
proxy configurations.
> Disable PGP verification in docker build

- README.md
The implementation version v1.0.0 complies to FIDO Device Onboard
Specification, but a note for earlier release was left out in the README
file claiming it to be a preliminary release.
Fixes issue #351 
> Remove disclaimer from README

- util/storage-samples/storage-di-sample/src/main/java/org/fidoalliance/fdo/storage/DiDbManager.java
- util/storage-samples/storage-di-sample/src/main/java/org/fidoalliance/fdo/storage/DiDbStorage.java
Fixing predictable authorized token issue in manufacturer.
Previously, the token was same as guid. Now we are
generating a random token for every guid.
This commit also introduces a database table for storing
DI session information. The table includes 4 attributes
sessionID, GUID, created & updated.
> Fixing predictable authorization token issue in manufacturer

- component-samples/demo/reseller/reseller.env
Fix to enable HTTPS port by default on reseller.
> Fix to enable HTTPS port by default on reseller

- component-samples/demo/scripts/keys_gen.sh
Fix keygen script to copy truststore file to creds/device.
> Fix keygen script to copy truststore file to device

- http-api-samples/http-api-di-sample/src/main/java/org/fidoalliance/fdo/api/DiApiServlet.java
Fixing the exception raised while extending the device with invalid
key formats. Now manufacturer returns a 500 error code, if invalid
key is present in the database.
> Fixing the exception raised while extending the device with invalid keyformat

- component-samples/aio/src/main/java/org/fidoalliance/fdo/sample/AioContextListener.java
Fixing TO0 scheduling issue in AIO.
Defect was a regression from Predictable token fix in manufacturer.
> Fixing TO0 scheduling issue in AIO

- pom.xml
CVE-2021-45046 was issued for Log4j 2.15.0 component.
It was found that the fix to address CVE-2021-44228 in
Apache Log4j 2.15.0 was incomplete, hence upgrading.
> Upgrading log4j version to 2.16.0 from 2.15.0

- pom.xml
CVE-2021-45046 was issued for Log4j 2.15.0 component.
It was found that the fix to address CVE-2021-44228 in
Apache Log4j 2.15.0 was incomplete, hence upgrading.
> Upgrading log4j version to 2.16.0

- component-samples/demo/aio/WEB-INF/web.xml
- component-samples/demo/aio/service.yml
- component-samples/demo/device/service.yml
- protocol/src/main/java/org/fidoalliance/fdo/protocol/api/AioRvInfo.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/api/CertificateApi.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/api/CertificateValidityApi.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/api/DeviceInfo.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/api/HealthApi.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/api/MessageSizeApi.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/api/RestApi.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/api/RestApiServlet.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/api/SviSizeApi.java
Following REST endpoints are added to protocol:
- POST /api/v1/aio/rvinfo?ip=<ip-address>&rvprot=<protocol>
- GET /health
- GET api/v1/certificate/validity
- POST api/v1/certificate/validity?days=<num-of-days>
- GET /ap1/v1/deviceinfo/{nseconds}
-- {nseconds} is optional, defaults to 20 seconds
- GET /api/v1/certificate?filename=filename.p12
- POST /api/v1/certificate?filename=filename.p12 with file in the body (binary)
- DELETE /api/v1/certificate?filename=filename.p12
- GET /api/v1/owner/messagesize
- POST /api/v1/owner/messagesize  Body with value
- GET /api/v1/owner/svithreshold
- POST /api/v1/owner/svithreshold body with value
> Adding new REST endpoints to protocol

- component-samples/demo/README.MD
- component-samples/demo/aio/docker-compose.yml
- component-samples/demo/manufacturer/docker-compose.yml
- component-samples/demo/reseller/docker-compose.yml
- Enable host networking mode on docker/podman
- Readme updates
Signed-off-by: Shrikant Temburwar <shrikant.temburwar@intel.com>
> Enable host networking mode on docker/podman

- component-samples/demo/aio/service.yml
- component-samples/demo/owner/WEB-INF/web.xml
- component-samples/demo/owner/service.yml
This PR contains:
1. Replacement voucher API's endpoint to owner's web.xml
2. Removing the proxy values from AIO's service.yml and removing a duplicate worker comment
3. Adding the Reuse worker comment to owner's service.yml
Signed-off-by: Himanshu <himanshu@intel.com>
> Added replacement voucher API endpoint

- component-samples/demo/owner/service.yml
Enabling BasicServiceInfoClientSupplier worker by default.
> Enabling BasicServiceInfoClientSupplier worker

- build/README.md
- build/docker-compose.yml
Enable Docker build on Ubuntu 22.
> Enable Docker build on Ubuntu 22

- component-samples/demo/aio/README.md
- component-samples/demo/aio/service.yml
- component-samples/demo/manufacturer/service.yml
- component-samples/demo/owner/README.md
- component-samples/demo/owner/service.yml
- component-samples/demo/reseller/README.md
- component-samples/demo/reseller/service.yml
- component-samples/demo/rv/service.yml
- protocol/src/main/java/org/fidoalliance/fdo/protocol/FileKeyStoreInputStream.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/FileKeyStoreOutputStream.java
Adding support for importing keystores from FileSystem.
Supports PKCS12 formatted Keystores.
> Reading Keystores from FileSystem

- component-samples/demo/scripts/extend_upload.sh
Updating extend_upload.sh script to support both mTLS and Digest Auth.
Signed-off-by: Anapareddy, Sai Anudeep <sai.anudeep.anapareddy@intel.com>
> Updating extend_upload.sh script to support both mTLS and Digest Auth

- protocol/pom.xml
Upgrading H2 to latest version:
H2 database 2.1.210 ==> 2.1.214.
> Upgrading H2 to latest version

- component-samples/aio/pom.xml
- pom.xml
commons-text 1.9 ==> 1.10.0
jackson-databind 2.13.3 ==> 2.14.2
removing derby dependency.
> Upgrading dependencies to latest version

- component-samples/demo/aio/docker-compose.yml
- component-samples/demo/db/docker-compose.yml
- component-samples/demo/device/docker-compose.yml
- component-samples/demo/manufacturer/docker-compose.yml
- component-samples/demo/owner/docker-compose.yml
- component-samples/demo/reseller/docker-compose.yml
- component-samples/demo/rv/docker-compose.yml
Updating docker-compose files to be compatible with Ubuntu 20.04 LTS.
> Updating docker-compose files to be compatible with Ubuntu 20.04 LTS

- component-samples/demo/aio/service.yml
- component-samples/demo/manufacturer/service.yml
- component-samples/demo/owner/service.yml
- component-samples/demo/rv/service.yml
- protocol/src/main/java/org/fidoalliance/fdo/protocol/EpidService.java
- protocol/src/test/resources/service.yml
Modifying the default EPID url to verifier.fdorv.com
> Modifying the default EPID url

- protocol/src/main/java/org/fidoalliance/fdo/protocol/StandardMessageDispatcher.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/UntrustedRendezvousAcceptFunction.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/db/TrustedRendezvousAcceptFunction.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/dispatch/RendezvousAcceptFunction.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/message/To0OwnerSign2.java
5.3.3. TO0.OwnerSign, Type 22 tod0 is supposed to be encoded as a bstr.  RV server has been updated to handle both non compliant to0d as an array as well as spec compliant to0d encoded as a bstr.  Owner has been updated to always send spec compliant to0d encoded as a bstr.  Devices are unaffected.
> fixed message 22 ownershign to0d bstr encoding issue

- pom.xml
Upgrading Jackson Databind Library from 2.15.0 ==> 2.15.2
> Upgrading Jackson Databind Library

- component-samples/demo/scripts/keys_gen.sh
**Bug Description**
component-samples/demo/scripts/keys_gen.sh is used to generate environmental variables and secrets folder to store client  and server key pairs. One of the command `openssl rand --base64 12` in the shell script is used to generate db_password and encrypt_password. This is incorrect way of using it to generate password, the correct way is `openssl rand -base64 12`
**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'component-samples/demo/scripts/'
2. Click on 'keys_gen.sh'
3. Scroll down to 'line no 54, 55, 71'
4. change `openssl rand --base64 12 | tr -dc 0-9A-Za-z` to `openssl rand -base64 12 | tr -dc 0-9A-Za-z`
> Update to command generating random password in keys_gen.sh

- component-samples/demo/README.MD
Documentation update:
1. Added 'owner_exec' command for generic execution which can perform various tasks such as downloading files, running scripts, and executing commands.
2. Included a sample SVI instruction with 'owner_exec' for reference.
> Add owner_exec docs to FDO PRI 

- component-samples/device/src/main/java/org/fidoalliance/fdo/sample/FdoSysDeviceModule.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/db/FdoSysOwnerModule.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/serviceinfo/FdoSys.java
Currently fetch is just printing the contents of the fetched file from client.
We are changing fetch to pull files from client side
and store it in app-data folder.
> Draft implementation of FDO_SYS:fetch

- protocol/src/main/java/org/fidoalliance/fdo/protocol/HttpUtils.java
Defaulting to HTTPS when RV_SCHEME is not provided.
> Defaulting to HTTPS when RV_SCHEME is not provided

- protocol/src/main/java/org/fidoalliance/fdo/protocol/StandardMessageDispatcher.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/message/RendezvousConstant.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/serialization/RendezvousInstructionDeserializer.java
1. **GUID Field in OV Header**: Prevents empty values in the GUID Field.
2. **Protocol Version in OV Header**: Ensures only "101" is accepted as the protocol version.
3. **RVDevPort Type in OV Header**: Accepts only "3" as the RVDevPort Type and checks for null values in RVDevPort Value.
4. **RVDNS Type in OV Header**: Accepts only "5" as the RVDNS Type and checks for null values in RVDNS Value.
5. **RVOwnerPort Type in OV Header**: Accepts only "4" as the RVOwnerPort Type and checks for null values in RVOwnerPort Value.
6. **RVProtocol Type in OV Header**: Accepts only "12" as the RVProtocol Type.
7. **RVProtocol Value in OV Header**: Accepts only "1" or "2" as the RVProtocol Value.
8. **Encoding of Mfg Pubkey in OV Header**: Ensures values like "+0.0" and "003" are not accepted.
> [Fixed] Fuzzing TO0 message 22 issues

- protocol/src/main/java/org/fidoalliance/fdo/protocol/Config.java
Original value was used to resolve Env values. This would break when having multiple environment variable defined in the string value given to the `getEnvValue`.
> Fix getEnvValue to support multiple env variables

- component-samples/device/src/main/java/org/fidoalliance/fdo/sample/DeviceApp.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/HttpUtils.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/StandardTo0Client.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/db/AutoInjectVoucherStorageFunction.java
Fixing TO0 Scheme selection issue when both ownerPort & devport is
identical.
> Fixing TO0 Scheme selection issue

- protocol/src/main/java/org/fidoalliance/fdo/protocol/StandardCryptoService.java
- protocol/src/main/java/org/fidoalliance/fdo/protocol/message/DiffieHellman.java
1. The device's secret gets set to null in an erroneous call to destroy before it is used to compute the shared secret, thus causing `modPow` to throw an exception.
2. The DiffieHellman.KeyExchange type cannot reconstruct itself from an `AnyType` without a `@JsonCreator`-annotated constructor.
3. The shared secret is sometimes 1 extra byte in length, due to the behavior of `BigInteger.toBytes()`. See https://stackoverflow.com/questions/24158629/biginteger-tobytearray-returns-purposeful-leading-zeros.
> Fix Diffie Hellman key exchange

- component-samples/demo/aio/service.yml
Reverts fido-device-onboard/pri-fidoiot#699
The PR should have been closed without merging as it was only opened as a way to test debugging, @uhofemeier.
> Revert "Update service.yml"

- component-samples/aio/pom.xml
- pom.xml
This PR fix vulnerability in mysql-connector-j(https://github.com/advisories/GHSA-m6vm-37g8-gqvh) and protobuf-java(https://github.com/advisories/GHSA-735f-pc8j-v9w8).  #705
Mysql-connector-j 8.2.0 still brings in a vulnerable version of protobuf-java (3.21.9) as a transitive dependency.  Mysql-connector-j 9.1.0 includes a fixed version of protobuf-java but I am worried that upgrading to 9.x may introduce compatibility issues. Therefore this PR upgrades mysql-connector-j to 8.2.0 to fix MySQL-related vulnerabilities and explicitly sets protobuf-java to 4.28.2 to avoid the transitive vulnerability
> upgrade mysql and protobuf to fix vulnerability

- pom.xml
**Description:** https://github.com/fido-device-onboard/pri-fidoiot/issues/705
Fix CVE-2024-34750/CVE-2024-50379
`- Tomcat has been updated to version 11.0.6`
> Fix CVE-2024-34750/CVE-2024-50379
